language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

before_install:
  - script/up

script:
  - script/test

jobs:
  include:
    - stage: distribute
      if: branch = master AND type != pull_request
      install: skip
      script:
        - script/distribute
