#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Set up public GC creds.
export GCLOUD_ACCOUNT=$(cat tests/files/gcloud.json.enc)

# Run tests and lint checks.
PYTHONPATH="." pytest $ARGS
flake8 --max-line-length 50000 stored