#!/usr/bin/env bash
. script/env
ARGS="${@:-tests/}"
set -e

# Set up public GC creds.
mkdir -p .cache/test
base64 --decode tests/files/gcloud.json.enc > .cache/test/gcloud.json
export GOOGLE_APPLICATION_CREDENTIALS=".cache/test/gcloud.json"

# Run tests and lint checks.
PYTHONPATH="." pytest $ARGS
flake8 --max-line-length 50000 stored